"""
Streamlit dashboard for saved RAG evaluation reports.

Run with:
    streamlit run rag_dashboard.py
"""

import json
from html import escape
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st


REPORTS_DIR = Path("reports")
GENERATION_METRIC_KEYS = [
    "faithfulness",
    "answer_relevancy",
    "context_precision",
    "context_recall",
    "rouge_l",
]
RETRIEVAL_METRIC_KEYS = [
    "hit_at_5",
    "mrr",
    "id_context_precision",
    "id_context_recall",
]
METRIC_KEYS = GENERATION_METRIC_KEYS + RETRIEVAL_METRIC_KEYS
LATENCY_KEYS = [
    "average_case_duration_ms",
    "p50_case_duration_ms",
    "p95_case_duration_ms",
    "max_case_duration_ms",
]
METRIC_HELP = {
    "faithfulness": "How well the answer stays supported by the retrieved context.",
    "answer_relevancy": "How directly the generated answer addresses the user's question.",
    "context_precision": "How much of the retrieved context is useful instead of irrelevant filler.",
    "context_recall": "How much of the information needed for the expected answer was retrieved.",
    "rouge_l": "How closely the generated answer's wording overlaps with the golden answer.",
    "hit_at_5": "Whether at least one expected reference chunk appeared in the top five results.",
    "mrr": "How highly the first expected reference chunk appeared in the ranked results.",
    "id_context_precision": "The share of retrieved chunks that match reviewed reference chunks.",
    "id_context_recall": "The share of reviewed reference chunks that retrieval successfully found.",
}
USAGE_HELP = {
    "total_tokens": "Total input and output tokens used across the evaluation run.",
    "input_tokens": "Tokens sent to models across the evaluation run.",
    "output_tokens": "Tokens generated by models across the evaluation run.",
    "known_cost_usd": "Estimated cost for models with prices configured in the environment.",
}
LATENCY_HELP = {
    "average_case_duration_ms": "Average time required to evaluate one test case.",
    "p50_case_duration_ms": "Half of the evaluated cases completed within this time.",
    "p95_case_duration_ms": "Ninety-five percent of evaluated cases completed within this time.",
    "max_case_duration_ms": "Longest time taken by any evaluated case.",
}


def section_label(label: str, help_text: str = "") -> None:
    title = f' title="{escape(help_text)}"' if help_text else ""
    st.markdown(f'<div class="section-label"{title}>{escape(label)}</div>', unsafe_allow_html=True)


def apply_theme() -> None:
    st.markdown(
        """
        <style>
        :root {
            --dashboard-border: rgba(148, 163, 184, 0.32);
            --dashboard-muted: rgba(100, 116, 139, 0.96);
            --dashboard-card-bg: var(--secondary-background-color);
            --dashboard-text: var(--text-color);
            --dashboard-label: rgba(100, 116, 139, 0.98);
        }

        @media (prefers-color-scheme: dark) {
            :root {
                --dashboard-border: rgba(148, 163, 184, 0.24);
                --dashboard-muted: rgba(203, 213, 225, 0.82);
                --dashboard-label: rgba(203, 213, 225, 0.88);
            }
        }

        .block-container {
            max-width: 1380px;
            padding-top: 3rem;
            padding-bottom: 4rem;
        }

        [data-testid="stSidebar"] {
            border-right: 1px solid var(--dashboard-border);
        }

        .dashboard-header {
            border-bottom: 1px solid var(--dashboard-border);
            margin-bottom: 1.6rem;
            padding-bottom: 1.2rem;
        }

        .dashboard-kicker {
            color: var(--dashboard-muted);
            font-size: 0.82rem;
            font-weight: 650;
            letter-spacing: 0;
            margin: 0 0 0.35rem;
        }

        .dashboard-title {
            color: var(--dashboard-text);
            font-size: 2.15rem;
            font-weight: 720;
            line-height: 1.18;
            letter-spacing: 0;
            margin: 0;
        }

        .dashboard-meta {
            color: var(--dashboard-muted);
            font-size: 0.94rem;
            line-height: 1.55;
            margin-top: 0.7rem;
            overflow-wrap: anywhere;
        }

        .section-label {
            color: var(--dashboard-text);
            font-size: 1.05rem;
            font-weight: 700;
            letter-spacing: 0;
            margin: 1.8rem 0 0.7rem;
        }

        [data-testid="stMetric"] {
            background: var(--dashboard-card-bg);
            border: 1px solid var(--dashboard-border);
            border-radius: 8px;
            min-height: 112px;
            padding: 1rem 1.1rem;
        }

        [data-testid="stMetricLabel"] p {
            color: var(--dashboard-label);
            font-size: 0.86rem;
        }

        [data-testid="stMetricValue"] {
            color: var(--dashboard-text);
            font-size: 1.55rem;
        }

        [data-testid="stMetricDelta"] {
            font-size: 0.86rem;
        }

        div[data-testid="stVerticalBlock"] > div:has(> [data-testid="stHorizontalBlock"]) {
            gap: 0.9rem;
        }

        .stAlert {
            margin-top: 0.9rem;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def load_reports(reports_dir: Path = REPORTS_DIR) -> list[dict[str, Any]]:
    if not reports_dir.exists():
        return []
    reports: list[dict[str, Any]] = []
    for path in sorted(reports_dir.glob("*.json"), reverse=True):
        try:
            report = json.loads(path.read_text(encoding="utf-8"))
            report["_path"] = str(path)
            reports.append(report)
        except Exception:
            continue
    return reports


def summary_frame(reports: list[dict[str, Any]]) -> pd.DataFrame:
    rows = []
    for report in reports:
        summary = report.get("summary", {})
        ragas = report.get("ragas", {})
        usage = report.get("usage", {})
        latency = report.get("latency", {})
        row = {
            "run_id": report.get("run_id", ""),
            "created_at": report.get("created_at", ""),
            "test_set": report.get("test_set", ""),
            "cases": summary.get("cases", 0),
            "ragas_status": ragas.get("status", "not_requested"),
            "total_tokens": usage.get("total_tokens", 0),
            "known_cost_usd": usage.get("known_cost_usd", 0.0),
            "path": report.get("_path", ""),
        }
        for key in METRIC_KEYS:
            row[key] = summary.get(key)
        for key in LATENCY_KEYS:
            row[key] = latency.get(key)
        rows.append(row)
    return pd.DataFrame(rows)


def case_frame(report: dict[str, Any]) -> pd.DataFrame:
    rows = []
    ragas_cases = report.get("ragas", {}).get("cases", [])
    for case in report.get("cases", []):
        metrics = case.get("metrics", {})
        row = {
            "index": case.get("index"),
            "question": case.get("question", ""),
            "reason": case.get("reason", ""),
            "error": case.get("error", ""),
            "case_type": case.get("case_type", ""),
            "reviewed": case.get("reviewed"),
            "reviewer": case.get("reviewer", ""),
            "reference_chunks": ", ".join(case.get("reference_chunks") or []),
            "tags": ", ".join(case.get("tags") or []),
        }
        usage = case.get("usage") or {}
        row["total_tokens"] = usage.get("total_tokens", 0)
        row["known_cost_usd"] = usage.get("known_cost_usd", 0.0)
        row["unknown_cost_stages"] = ", ".join(usage.get("unknown_cost_stages") or [])
        for key in METRIC_KEYS:
            row[key] = metrics.get(key)
        if ragas_cases and len(ragas_cases) >= int(case.get("index", 0)):
            ragas_row = ragas_cases[int(case["index"]) - 1]
            for key in ("faithfulness", "answer_relevancy", "context_precision", "context_recall"):
                if key in ragas_row:
                    row[f"ragas_{key}"] = ragas_row[key]
        rows.append(row)
    return pd.DataFrame(rows)


def populated_columns(df: pd.DataFrame, columns: list[str]) -> list[str]:
    return [column for column in columns if column in df.columns and df[column].notna().any()]


def metric_delta(current: dict[str, Any], previous: dict[str, Any] | None, key: str) -> float | None:
    if not previous:
        return None
    current_value = current.get("summary", {}).get(key)
    previous_value = previous.get("summary", {}).get(key)
    if current_value is None or previous_value is None:
        return None
    return float(current_value) - float(previous_value)


def main() -> None:
    st.set_page_config(page_title="RAG Eval Dashboard", layout="wide")
    apply_theme()

    reports = load_reports()
    if not reports:
        st.markdown(
            """
            <div class="dashboard-header">
              <p class="dashboard-kicker">Local RAG Evaluation</p>
              <h1 class="dashboard-title">RAG Eval Dashboard</h1>
            </div>
            """,
            unsafe_allow_html=True,
        )
        st.info("No reports found. Run `python evaluate_rag.py .\\rag_eval_set.json` first.")
        return

    df = summary_frame(reports)
    selected_run = st.sidebar.selectbox(
        "Report",
        options=df["run_id"].tolist(),
        format_func=lambda run_id: f"{run_id} ({df.loc[df['run_id'] == run_id, 'cases'].iloc[0]} cases)",
        help="Choose which saved evaluation report to inspect.",
    )
    selected_index = df.index[df["run_id"] == selected_run][0]
    report = reports[int(selected_index)]
    previous_report = reports[int(selected_index) + 1] if int(selected_index) + 1 < len(reports) else None
    report_path = escape(str(report.get("_path", "")))
    selected_run_label = escape(str(selected_run))

    st.markdown(
        f"""
        <div class="dashboard-header">
          <p class="dashboard-kicker">Local RAG Evaluation</p>
          <h1 class="dashboard-title">RAG Eval Dashboard</h1>
          <div class="dashboard-meta">
            <strong>{selected_run_label}</strong><br>
            {report_path}
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    usage = report.get("usage", {})
    section_label("Run Usage", "Tokens and estimated model cost consumed by this evaluation run.")
    usage_cols = st.columns(4, gap="large")
    usage_cols[0].metric("Eval Tokens", f"{int(usage.get('total_tokens') or 0):,}", help=USAGE_HELP["total_tokens"])
    usage_cols[1].metric("Input Tokens", f"{int(usage.get('total_input_tokens') or 0):,}", help=USAGE_HELP["input_tokens"])
    usage_cols[2].metric("Output Tokens", f"{int(usage.get('total_output_tokens') or 0):,}", help=USAGE_HELP["output_tokens"])
    usage_cols[3].metric("Known Cost", f"${float(usage.get('known_cost_usd') or 0.0):.6f}", help=USAGE_HELP["known_cost_usd"])
    unknown_stages = usage.get("unknown_cost_stages") or []
    if unknown_stages:
        st.info(
            "Cost is partial. Add prices to `GROQ_MODEL_PRICES_JSON` for: "
            + ", ".join(sorted(set(unknown_stages)))
        )

    latency = report.get("latency", {})
    if latency:
        section_label("Latency", "How long evaluation cases took to complete.")
        latency_cols = st.columns(4, gap="large")
        latency_cols[0].metric("Average Case", f"{float(latency.get('average_case_duration_ms') or 0.0):,.0f} ms", help=LATENCY_HELP["average_case_duration_ms"])
        latency_cols[1].metric("P50 Case", f"{float(latency.get('p50_case_duration_ms') or 0.0):,.0f} ms", help=LATENCY_HELP["p50_case_duration_ms"])
        latency_cols[2].metric("P95 Case", f"{float(latency.get('p95_case_duration_ms') or 0.0):,.0f} ms", help=LATENCY_HELP["p95_case_duration_ms"])
        latency_cols[3].metric("Max Case", f"{float(latency.get('max_case_duration_ms') or 0.0):,.0f} ms", help=LATENCY_HELP["max_case_duration_ms"])

    section_label("Generation Scores", "Measures whether the final answer is grounded, relevant, and close to the expected answer.")
    generation_cols = st.columns(len(GENERATION_METRIC_KEYS), gap="large")
    for col, key in zip(generation_cols, GENERATION_METRIC_KEYS):
        value = report.get("summary", {}).get(key)
        delta = metric_delta(report, previous_report, key)
        label = "n/a" if value is None else f"{float(value):.2f}"
        col.metric(key.replace("_", " ").title(), label, None if delta is None else f"{delta:+.2f}", help=METRIC_HELP[key])

    retrieval_summary_keys = [key for key in RETRIEVAL_METRIC_KEYS if report.get("summary", {}).get(key) is not None]
    if retrieval_summary_keys:
        section_label("Retrieval Scores", "Measures whether retrieval found and ranked the reviewed reference chunks correctly.")
        retrieval_cols = st.columns(len(retrieval_summary_keys), gap="large")
        for col, key in zip(retrieval_cols, retrieval_summary_keys):
            value = report.get("summary", {}).get(key)
            delta = metric_delta(report, previous_report, key)
            col.metric(key.replace("_", " ").title(), f"{float(value):.2f}", None if delta is None else f"{delta:+.2f}", help=METRIC_HELP[key])

    thresholds = report.get("thresholds", {})
    if thresholds.get("checks"):
        if thresholds.get("passed"):
            st.success("Configured regression thresholds passed.")
        else:
            st.error("Configured regression thresholds failed.")
            st.dataframe(pd.DataFrame(thresholds.get("failures") or []), width="stretch", hide_index=True)

    ragas = report.get("ragas", {})
    if ragas.get("status") == "ok":
        st.success("RAGAS metrics available for this run.")
        ragas_cols = st.columns(4, gap="large")
        for col, key in zip(ragas_cols, ("faithfulness", "answer_relevancy", "context_precision", "context_recall")):
            col.metric(f"RAGAS {key.replace('_', ' ').title()}", f"{float(ragas['summary'].get(key, 0.0)):.2f}", help=METRIC_HELP[key])
    elif ragas.get("status") not in {None, "not_requested"}:
        st.warning(f"RAGAS status: {ragas.get('status')} - {ragas.get('error', '')}")

    st.divider()
    st.subheader("Trends", help="Shows how quality, retrieval, latency, and cost metrics change across saved evaluation runs.")
    trend_df = df.sort_values("created_at")
    generation_trends = populated_columns(trend_df, GENERATION_METRIC_KEYS)
    retrieval_trends = populated_columns(trend_df, RETRIEVAL_METRIC_KEYS)
    latency_trends = populated_columns(trend_df, LATENCY_KEYS)
    if generation_trends:
        st.line_chart(trend_df.set_index("run_id")[generation_trends])
    if retrieval_trends:
        st.line_chart(trend_df.set_index("run_id")[retrieval_trends])
    if latency_trends:
        st.line_chart(trend_df.set_index("run_id")[latency_trends])
    if {"total_tokens", "known_cost_usd"}.issubset(trend_df.columns):
        st.line_chart(trend_df.set_index("run_id")[["total_tokens", "known_cost_usd"]])

    st.subheader("Cases", help="Inspect individual test cases to understand why a score passed or failed.")
    cases_df = case_frame(report)
    threshold = st.slider(
        "Show cases with any metric below",
        0.0,
        1.0,
        0.75,
        0.05,
        help="Sets the score below which a case is considered a failure in this table.",
    )
    metric_columns = populated_columns(cases_df, METRIC_KEYS)
    failing_mask = cases_df[metric_columns].lt(threshold).any(axis=1) if metric_columns else []
    show_failures_only = st.toggle(
        "Failures only",
        value=False,
        help="Show only cases with at least one score below the selected threshold.",
    )
    visible_df = cases_df[failing_mask] if show_failures_only and metric_columns else cases_df
    st.dataframe(visible_df, width="stretch", hide_index=True)

    selected_case = st.selectbox(
        "Inspect case",
        options=[case.get("index") for case in report.get("cases", [])],
        help="Choose an individual evaluation case to inspect in detail.",
    )
    case = next(item for item in report.get("cases", []) if item.get("index") == selected_case)

    left, right = st.columns(2, gap="large")
    with left:
        st.markdown("**Question**")
        st.write(case.get("question", ""))
        st.markdown("**Generated answer**")
        st.write(case.get("generated_answer", ""))
        st.markdown("**Golden answer**")
        st.write(case.get("golden_answer", ""))
    with right:
        st.markdown("**Judge reason**")
        st.write(case.get("reason", ""))
        st.markdown("**Retrieved context**")
        st.text_area(
            "Context",
            value=case.get("context", ""),
            height=420,
            label_visibility="collapsed",
            help="The passages retrieved and supplied to the answer model.",
        )


if __name__ == "__main__":
    main()
